--- 
attribution: "openrouteservice.org | OpenStreetMap contributors | Who's On First, whosonfirst.mapzen.com | GeoNames, www.geonames.org"
maximum_categories: 5
maximum_feature_area: -1
maximum_feature_length: 10000000
maximum_search_radius_for_linestrings: 1000
maximum_search_radius_for_points: 20000
maximum_search_radius_for_polygons: 1000
response_limit: 20000
osm_file: bremen-latest.osm.pbf
osm_file_tests: bremen-tests.pbf
provider_parameters:
  table_name: ops_planet_pois
  db_name: gis
  user_name: gis_admin
  password: admin
  host: localhost
  port: 5433
column_mappings:
  # https://wiki.openstreetmap.org/wiki/Key:name
  name:
    common_values: ['str']
    filterable: 'like'
  # https://wiki.openstreetmap.org/wiki/Key:wheelchair
  wheelchair:
    common_values: ['yes', 'limited', 'no', 'designated']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:smoking
  smoking:
    common_values: ['dedicated','yes','separated','isolated', 'no', 'outside']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:fee
  fee:
    common_values: ['yes','no', 'str']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:opening_hours
  opening_hours:
  # https://wiki.openstreetmap.org/wiki/Key:phone
  phone:
  # https://wiki.openstreetmap.org/wiki/Key:website
  website: