--- 
attribution: "openrouteservice.org | OpenStreetMap contributors | Who's On First, whosonfirst.mapzen.com | GeoNames, www.geonames.org"
maximum_categories: 5
maximum_feature_area: -1
maximum_feature_length: 10000000
maximum_search_radius_for_linestrings: 1000
maximum_search_radius_for_points: 20000
maximum_search_radius_for_polygons: 1000
provider_parameters:
  table_name: ops_planet_pois
  db_name: gis
  user_name: gis_admin
  password: admin
  host: localhost
  port: 5433
response_limit: 1000