--- 
attribution: "openrouteservice.org | OpenStreetMap contributors | Who's On First, whosonfirst.mapzen.com | GeoNames, www.geonames.org"
maximum_categories: 5
maximum_feature_area: -1
maximum_feature_length: 10000000
maximum_search_radius_for_linestrings: 1000
maximum_search_radius_for_points: 20000
maximum_search_radius_for_polygons: 1000
osm_file: austria-latest.osm.pbf
provider_parameters:
  table_name: ops_planet_pois
  db_name: gis
  user_name: gis_admin
  password: admin
  host: localhost
  port: 5433
column_mappings:
  # https://wiki.openstreetmap.org/wiki/Key:name
  name:
    common_values: ['str']
    filterable: 'like'
  # https://wiki.openstreetmap.org/wiki/Key:wheelchair
  wheelchair:
    common_values: ['yes', 'limited', 'no', 'designated']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:smoking
  smoking:
    common_values: ['dedicated','yes','separated','isolated', 'no', 'outside']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:fee
  fee:
    common_values: ['yes','no', 'str']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:opening_hours
  opening_hours:
  # https://wiki.openstreetmap.org/wiki/Key:phone
  phone:
  # https://wiki.openstreetmap.org/wiki/Key:website
  website:


response_limit: 1000


             #   if tag == 'name':
             #   self.name = value

           # elif tag == 'wheelchair':
            #    self.wheelchair_access = 'yes' if value == 'true' else 'no'
            #    self.wheelchair_access = value

           # elif tag == 'smoking':
           #     self.smoking = 'yes' if value == 'true' else 'no'
           #     self.smoking = value

           # elif tag == 'fee':
           #     self.fee = value

           # elif tag == 'opening_hours':
           #     self.opening_hours = value

           # elif tag == 'phone' or tag == 'contact:phone':
           #     self.phone = value

           # elif tag == 'website':
           #    self.website = value

       #self.name = None
       # self.wheelchair_access = None
       # self.smoking = None
       # self.fee = None
       # self.opening_hours = None
       # self.phone = None
       # self.website = None
       # self.address = None

       #name = db.Column(db.Text, index=True, nullable=True)
   # website = db.Column(db.Text, nullable=True)
    #phone = db.Column(db.Text, nullable=True)
   # opening_hours = db.Column(db.Text, nullable=True)
    #wheelchair = db.Column(db.Text, nullable=True)
    #smoking = db.Column(db.Text, nullable=True)
    #fee = db.Column(db.Text, nullable=True)
    #address = db.Column(db.Text, nullable=True)