version: '2.2'
services:
 api:
  container_name: ops-api
  build: .
  volumes:
  - ./osm:/deploy/app/osm
  - ./ops_settings_docker_standalone.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  ports:
   - "5000:5000"
  mem_limit: 28g

 init:
  container_name: ops-init
  build: .
  environment:
   - INIT_DB=1
  volumes:
  - ./osm:/deploy/app/osm
  - ./import-log.json:/deploy/app/import-log.json
  - ./ops_settings_docker_standalone.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  mem_limit: 28g
  profiles:
   - initialize

 update:
  container_name: ops-update
  build: .
  environment:
   - UPDATE_DB=1
  volumes:
  - ./osm:/deploy/app/osm
  - ./import-log.json:/deploy/app/import-log.json
  - ./ops_settings_docker_standalone.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  mem_limit: 28g
  profiles:
   - update
