version: '2.2'
services:
 ops-api:
  container_name: ops-api
  build: .
  volumes:
  - ./osm:/deploy/app/osm
  - ./ops_settings_docker_standalone.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  ports:
   - "5000:5000"
  mem_limit: 28g

 ops-rebuild:
  container_name: ops-rebuild
  build: .
  environment:
   - REBUILD_DB=1
  volumes:
  - ./osm:/deploy/app/osm
  - ./ops_settings_docker_standalone.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  mem_limit: 28g
  profiles:
   - rebuild

 ops-update:
  container_name: ops-update
  build: .
  environment:
   - UPDATE_DB=1
  volumes:
  - ./osm:/deploy/app/osm
  - ./ops_settings_docker_standalone.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  mem_limit: 28g
  profiles:
   - update

