version: '2.2'
services:
 gunicorn_flask:
  #network_mode: "host"
  build: .
  environment:
   - REBUILD_DB=1
  volumes:
   - ./osm:/deploy/app/osm
   - ./ops_settings_docker.yml:/deploy/app/openpoiservice/server/ops_settings.yml
   - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  ports:
   - "5000:5000"
  mem_limit: 28g
