--- 
attribution: "openrouteservice.org | OpenStreetMap contributors"
maximum_categories: 5
# meters
maximum_search_radius_for_linestrings: 2000
maximum_search_radius_for_points: 2000
maximum_search_radius_for_polygons: 2000
# square meters
maximum_area: 25000
# meters
maximum_linestring_length: 500000
# limit of pois
response_limit: 2000
osm_file: bremen-latest.osm.pbf
osm_file_tests: bremen-tests.osm.pbf

provider_parameters:
  table_name: ops_planet_pois
  db_name: gis
  user_name: gis_admin
  password: admin
  host: localhost
  port: 5433
column_mappings:
  # https://wiki.openstreetmap.org/wiki/Key:name
  name:
    common_values: ['str']
    filterable: 'like'
  # https://wiki.openstreetmap.org/wiki/Key:wheelchair
  wheelchair:
    common_values: ['yes', 'limited', 'no', 'designated']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:smoking
  smoking:
    common_values: ['dedicated','yes','separated','isolated', 'no', 'outside']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:fee
  fee:
    common_values: ['yes','no', 'str']
    filterable: 'equals'
  # https://wiki.openstreetmap.org/wiki/Key:opening_hours
  opening_hours:
  # https://wiki.openstreetmap.org/wiki/Key:phone
  phone:
  # https://wiki.openstreetmap.org/wiki/Key:website
  website: