name: run tests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install postgit
      uses: huaxk/postgis-action@v1
      with:
        postgresql db: 'gis'
        postgresql user: 'gis_admin'
        postgresql password: 'admin'
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install protobuf & proj
      run: sudo apt-get update && sudo apt-get install -y build-essential protobuf-compiler libprotobuf-dev proj-bin libproj-dev
    - name: Activate cache for python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install pip requirements
      run: pip install wheel -r requirements.txt
    - name: Run tests
      run: python manage.py test
